# Generated by Django 6.1 on 2026-09-29 00:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='administrativos/fotos/')),
                ('contrato', models.FileField(blank=True, help_text='Contrato de trabajo en formato PDF.', upload_to='administrativos/contratos/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('usuario', models.OneToOneField(blank=True, help_text='Cuenta con la que este funcionario inicia sesión.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrativo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'administrativo',
                'verbose_name_plural': 'administrativos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
