# Generated by Django 6.1 on 2026-09-30 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstudiantesApp', '0004_nota_docente_mantenedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='ficha_matricula',
            field=models.FileField(blank=True, upload_to='estudiantes/fichas/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='ficha de matrícula (PDF)'),
        ),
    ]
