"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv
from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables sensibles desde el archivo .env (no se sube a GitHub).
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if host.strip()]

# Orígenes confiables para formularios (POST) cuando se accede por IP o dominio.
CSRF_TRUSTED_ORIGINS = [
    origen for origen in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origen
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # API REST: Django REST Framework, tokens JWT y documentación Swagger/OpenAPI.
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'AdministrativosApp', #App de administrativos de colegio
    'DocentesApp',
    'EstudiantesApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'AdministrativosApp.context_processors.perfil_usuario',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Base de datos MySQL de WAMP; los datos de conexión vienen del archivo .env.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            # WAMP usa MyISAM por defecto, que no soporta llaves foráneas.
            'init_command': "SET default_storage_engine=INNODB, sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# En el servidor, collectstatic reúne aquí todos los archivos estáticos.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Archivos subidos por los usuarios (fotos y documentos PDF).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Rutas usadas por el sistema de autenticación.
# El login acepta el nombre de usuario o el correo de la cuenta.
AUTHENTICATION_BACKENDS = ['AdministrativosApp.backends.UsuarioOCorreoBackend']

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'inicio_por_perfil'
LOGOUT_REDIRECT_URL = 'login'

MESSAGE_TAGS = {
    message_constants.ERROR: 'danger',
}


# API REST (Django REST Framework)
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    # La API se autentica solo con tokens JWT (encabezado "Authorization: Bearer <token>").
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # Seguro por defecto: todo endpoint exige token salvo que se indique lo contrario.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Todas las respuestas en JSON.
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Errores siempre en JSON con el mismo formato y sin datos internos (config/api.py).
    'EXCEPTION_HANDLER': 'config.api.manejador_errores',
    # Límite de intentos en el login de la API para frenar ataques de fuerza bruta.
    'DEFAULT_THROTTLE_RATES': {'token': '10/minute'},
}

# Tokens JWT (SimpleJWT)
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html

SIMPLE_JWT = {
    # Access token de vida corta: si alguien lo roba, sirve por poco tiempo.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    # Refresh token para pedir un nuevo access token sin volver a ingresar la clave.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # Cada renovación entrega un refresh nuevo e invalida el anterior (lista negra).
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Documentación Swagger/OpenAPI (drf-spectacular)
# https://drf-spectacular.readthedocs.io/en/latest/settings.html

SPECTACULAR_SETTINGS = {
    'TITLE': 'API Colegio Digital',
    'DESCRIPTION': (
        'API RESTful de Colegio Digital: docentes, estudiantes, notas y funcionarios. '
        'Para usar los endpoints protegidos, obtén un token en /api/token/ y '
        'presiona "Authorize" escribiendo solo el access token.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Separa los campos que se envían de los que se reciben (más claro en Swagger).
    'COMPONENT_SPLIT_REQUEST': True,
    # Mantiene el token autorizado aunque se recargue la página de Swagger.
    'SWAGGER_UI_SETTINGS': {'persistAuthorization': True},
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
