# Generated by Django 6.1 on 2026-09-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cuenta', models.EmailField(max_length=254, unique=True)),
                ('rut', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
